#pragma config(Sensor, in7,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl6,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include <constants/Settings.c>

#include <util/Manager.c>
#include <util/Util.c>

#include <subsystems/Drivetrain.c>
#include <subsystems/Arm.c>

#include <tasks/ArmTasks.c>
#include <tasks/DrivetrainTasks.c>

#include <autons/Autons.c>

void pre_auton() {
  bStopTasksBetweenModes = true;
}

task autonomous() {
	wait1Msec(10000);
	startTask(scoreDriveBack);
	while (true) {
		abortTimeslice();
	}
}

task usercontrol() {
	startTask(driveWithController);
	startTask(moveArmWithController);
	while (true) {
		abortTimeslice();
	}
}
