#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in5,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in7,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl6,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include <constants/Settings.c>

#include <util/Manager.c>
#include <util/Util.c>

#include <subsystems/Drivetrain.c>
#include <subsystems/Arm.c>
#include <subsystems/Claw.c>

#include <tasks/ArmTasks.c>
#include <tasks/DrivetrainTasks.c>
#include <tasks/ClawTasks.c>

void pre_auton() {
  bStopTasksBetweenModes = true;
}

task autonomous() {
	startTask(armFollowSetpoint);
	setArmSetpoint(maxArmAngle);
	driveForwardDistance(5);
	wait1Msec(1000);
	setArmSetpoint(200);
	wait1Msec(500);
	driveBackwardsDistance(1);
	wait1Msec(1000);
	setArmSetpoint(50);
	turnDegreesRight(90); // change this based on alliance
	wait1Msec(1000);
	driveForwardDistance(3);
	while (true) {
		abortTimeslice();
	}
}

task usercontrol() {
	startTask(driveWithController);
	startTask(moveArmWithController);
	startTask(moveClawWithController);
	while (true) {
		abortTimeslice();
	}
}
