#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in5,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in7,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <constants/Settings.c>

#include <util/Manager.c>
#include <util/Util.c>

#include <subsystems/Drivetrain.c>
#include <subsystems/Arm.c>
#include <subsystems/Claw.c>

#include <tasks/ArmTasks.c>
#include <tasks/DrivetrainTasks.c>
#include <tasks/ClawTasks.c>

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main () {
	startTask(driveWithController);
	startTask(moveArmWithController);
	startTask(moveClawWithController);
	while (true) {
		abortTimeslice();
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
